# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3pPtyv14uAzxD1Ze4NjncYI0__5Ay_s
"""

# ——————————————
# 📦 تثبيت النسخ المطلوبة (لو تحتاج)
# !pip install requests==2.31.0 beautifulsoup4==4.12.2 pillow==9.5.0 transformers==4.34.0 gradio==3.51.1
# ——————————————

import requests
from PIL import Image
from io import BytesIO
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from transformers import BlipProcessor, BlipForConditionalGeneration
import gradio as gr

# تحميل النموذج من Hugging Face
processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-image-captioning-large"
)

model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large"
)

# دالة توليد التسميات من أي صفحة ويب
def generate_captions(url: str):
    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        return f"Error: Unable to access URL, status {response.status_code}"

    soup = BeautifulSoup(response.text, "html.parser")

    img_elements = soup.find_all("img")
    results = []

    for img_element in img_elements:
        img_url = (
            img_element.get("src") or
            img_element.get("data-src") or
            None
        )

        # srcset handling
        if not img_url and img_element.has_attr("srcset"):
            img_url = img_element["srcset"].split()[0]

        if not img_url:
            continue

        # تجاهل الصور SVG
        if ".svg" in img_url:
            continue

        # حل مسار الصورة ليصبح رابط كامل باستخدام urljoin
        img_url = urljoin(url, img_url)

        # تأكد إنه رابط صحيح
        if not img_url.startswith("http"):
            continue

        try:
            r = requests.get(img_url, timeout=10, headers=headers)
            raw_image = Image.open(BytesIO(r.content))

            # تجاهل الصور الصغيرة جدًا
            if raw_image.size[0] * raw_image.size[1] < 200:
                continue

            raw_image = raw_image.convert("RGB")

            # توليد التسمية باستخدام BLIP
            text = "the image of"
            inputs = processor(images=raw_image, text=text, return_tensors="pt")
            out = model.generate(**inputs, max_new_tokens=50)
            caption = processor.decode(out[0], skip_special_tokens=True)

            results.append((raw_image, f"{caption}\n{img_url}"))

        except:
            continue

    return results


# واجهة Gradio
iface = gr.Interface(
    fn=generate_captions,
    inputs=gr.Textbox(label="Enter any website URL"),
    outputs=gr.Gallery(label="Generated Captions", columns=2),
    title="Image Captioning from Any Website (BLIP)",
    description="Enter any webpage URL. The app extracts images and generates captions for them."
)

iface.launch(share=True)

